version: '2.1'

services:
  client:
    image: client
    container_name: client
    build: ./client
    volumes:
      - ./client/public/:/usr/local/apache2/htdocs/
    expose:
      - 80
    ports:
      - '3000:80'
    depends_on:
      - rest-api

  processor:
    image: processor
    container_name: processor
    build: ./processor
    volumes:
      - ./processor:/processor
      - /processor/node_modules
    depends_on:
      - validator
    environment:
      - VALIDATOR_URL=tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator:1.0
    container_name: validator
    expose:
      - 4004
    ports:
      - '4004:4004'
    # start the validator with an empty genesis batch
    entrypoint: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
          sawadm keygen &&
          sawtooth keygen my_key &&
          sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
          sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -v \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "

  settings-tp:
    image: hyperledger/sawtooth-settings-tp:1.0
    container_name: settings-tp
    depends_on:
      - validator
    entrypoint: settings-tp -v -C tcp://validator:4004

  rest-api:
    image: hyperledger/sawtooth-rest-api:1.0
    container_name: rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -v
        --connect tcp://validator:4004
        --bind rest-api:8008

  shell:
    image: hyperledger/sawtooth-shell:1.0
    container_name: shell
    depends_on:
      - rest-api
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
          sawtooth keygen
        fi;
        tail -f /dev/null
      "
